.TH XFCE4-TERMINAL-THEME-SELECTOR "1" "Mar 2026" "xfce4-terminal-theme-selector" "User Commands"

.SH NAME
xfce4-terminal-theme-selector \- simple curses-based theme selector for xfce4-terminal

.SH SYNOPSIS
.B xfce4-terminal-theme-selector

.SH DESCRIPTION
.B xfce4-terminal-theme-selector
is a simple curses-based application that allows switching xfce4-terminal color
themes from the command line.

It provides an interactive interface for selecting and applying available
terminal themes.

.SH AUTHOR
Written by Kirill Rekhov.

.SH REPORTING BUGS
Report bugs at: <https://github.com/krekhovx/xfce4-terminal-theme-selector/issues>

.SH COPYRIGHT
Copyright: 2026, Kirill Rekhov <krekhov.dev@gmail.com>
.br
License: GPL-3.0+
